-- 코드를 입력하세요
#
SELECT CATEGORY , MAX(PRICE ) AS MAX_PRICE , 
(SELECT PRODUCT_NAME FROM FOOD_PRODUCT WHERE CATEGORY = P.CATEGORY ORDER BY PRICE DESC LIMIT 1 ) PRODUCT_NAME
FROM FOOD_PRODUCT AS P
WHERE CATEGORY = "국" OR CATEGORY = "김치" OR CATEGORY = "식용유" OR CATEGORY = "과자"
GROUP BY CATEGORY
ORDER BY PRICE DESC