-- 코드를 입력하세요
SELECT CATEGORY  , SUM(SALES) as TOTAL_SALES 
FROM BOOK INNER JOIN BOOK_SALES ON BOOK.BOOK_ID  = BOOK_SALES.BOOK_ID
WHERE MONTH(SALES_DATE) = 1  AND YEAR(SALES_DATE) = 2022
GROUP BY CATEGORY
ORDER BY CATEGORY