-- 코드를 입력하세요
SELECT B.AUTHOR_ID , A.AUTHOR_NAME , B.CATEGORY , SUM(SALES*PRICE) AS TOTAL_SALES
FROM 
BOOK B 
LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY 1,2,3
ORDER BY 1 , 3 DESC